
module.exports.sociallyRestrictedSkills = [
  "hacking",
  "phishing",
  "spam",
  "ddos",
  "distributed denial of service",
  "sql injection",
  "xss",
  "cross-site scripting",
  "cracking",
  "black hat seo",
  "piracy",
  "password cracking",
  "social engineering",
  "malware development",
  "unauthorized access",
  "dark web navigation",
  "trojans",
  "viruses",
  "ransomware",
  "spyware",
  "exploiting vulnerabilities",
  "data theft",
  "illegal streaming",
  "identity theft",
  "cyber bullying",
  "fake news propagation",
  "plagiarism",
  "deepfake creation",
  "unauthorized surveillance",
  "cheating in online games",
];
